Controllers/InquilinosController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Inmobiliaria.Models;
using Microsoft.AspNetCore.Authorization;
namespace Inmobiliaria.Controllers;
[Authorize]
public class InquilinosController : Controller
{
    private readonly ILogger<InquilinosController> _logger;

    public InquilinosController(ILogger<InquilinosController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        InquilinosRepository repo = new InquilinosRepository();
        List<Inquilino> inquilinos = repo.GetAllInquilinos();

        return View(inquilinos);
    }

    public IActionResult Create()
    {


        return View();
    }


    [HttpPost]
    public IActionResult Create(Inquilino inquilino)
    {

        try
        {
            InquilinosRepository repo = new();
            var res = repo.CreateInquilino(inquilino);
            InmueblesRepository repo2 = new();
            var enumTipo = repo2.getEnumTipos();
            var enumUso = repo2.getEnumUso();
            ViewBag.enumTipo = enumTipo;
            ViewBag.enumUso = enumUso;

            string returnUrl = Request.Headers["Referer"].ToString();
            Uri refererUri = new Uri(returnUrl);
            string relativePath = refererUri.GetComponents(UriComponents.PathAndQuery, UriFormat.SafeUnescaped);
            Console.WriteLine(relativePath);
            if (res > 0)
            {

                TempData["AlertMessage"] = "Inquilino creado correctamente.";
                TempData["AlertType"] = "success";
                Console.WriteLine("RELATIVE PATH: " + relativePath);


                if (relativePath == "/Inquilinos/Create")
                {

                    return Redirect("index");
                }



            }
            else if (res == -1)
            {
                TempData["AlertMessage"] = "No se pudo crear el inquilino, Error en la base de datos.";
                TempData["AlertType"] = "error";

            }
            else if (res == -2)
            {
                TempData["AlertMessage"] = "No se pudo crear el inquilino, Ya existe uno con ese DNI.";
                TempData["AlertType"] = "error";

            }
            else if (res == -3)
            {
                TempData["AlertMessage"] = "No se pudo crear el inquilino, Ingrese un email valido.";
                TempData["AlertType"] = "error";

            }
            else if (res == -4)
            {
                TempData["AlertMessage"] = "No se pudo crear el inquilino, Ingrese un DNI valido.";
                TempData["AlertType"] = "error";

            }
            else
            {
                TempData["AlertMessage"] = "No se pudo crear el inquilino, Ya existe un propietario con ese DNI.";
                TempData["AlertType"] = "error";

            }
            return Redirect(relativePath);
        }
        catch (System.Exception)
        {
            throw;
        }

    }
    [HttpPost]
    [Authorize(Policy = "Administrador")]
    public IActionResult Delete(int id)
    {
        try
        {

            InquilinosRepository repo = new();
            repo.DeleteInquilino(id);
            return RedirectToAction("Index");
        }
        catch (System.Exception)
        {
            throw;
        }
    }
    public IActionResult Update(int id)
    {
        InquilinosRepository repo = new();
        var inquilino = repo.GetInquilinoById(id);
        return View(inquilino);
    }


    [HttpPost]
    public IActionResult Update(Inquilino inquilino)
    {

        string returnUrl = Request.Headers["Referer"].ToString();
        Uri refererUri = new Uri(returnUrl);
        string relativePath = refererUri.GetComponents(UriComponents.PathAndQuery, UriFormat.SafeUnescaped);
        try
        {
            InquilinosRepository repo = new();
            int res = repo.UpdateInquilino(inquilino);

            if (res > 0)
            {

                TempData["AlertMessage"] = "Inquilino modificado correctamente.";
                TempData["AlertType"] = "success";
                return RedirectToAction("Index");
            }
            else if (res == -1)
            {
                TempData["AlertMessage"] = "No se pudo modificar el inquilino, Error en la base de datos.";
                TempData["AlertType"] = "error";
                return Redirect(relativePath);
            }
            else if (res == -2)
            {
                TempData["AlertMessage"] = "No se pudo modificar el inquilino, Ingrese un numero telefonico valido.";
                TempData["AlertType"] = "error";
                return Redirect(relativePath);
            }
            else if (res == -3)
            {
                TempData["AlertMessage"] = "No se pudo modificar el inquilino, Ingrese un email valido.";
                TempData["AlertType"] = "error";
                return Redirect(relativePath);
            }
            else if (res == -4)
            {
                TempData["AlertMessage"] = "No se pudo modificar el inquilino, Ingrese un DNI valido.";
                TempData["AlertType"] = "error";
                return Redirect(relativePath);
            }
            else
            {
                TempData["AlertMessage"] = "No se pudo modificar el inquilino, Ya existe un inquilino con ese DNI.";
                TempData["AlertType"] = "error";
                return Redirect(relativePath);
            }
        }
        catch (System.Exception)
        {

            throw;
        }

    }

    public IActionResult Details(int id)
    {
        InquilinosRepository repo = new();
        var inquilino = repo.GetInquilinoById(id);
        return View(inquilino);
    }

    //APIS

    [HttpGet("api/Inquilios/GetInquilino/{dni}")]
    public IActionResult GetInquilino(string dni)
    {
        // Aquí, realiza la lógica para buscar el propietario por DNI
        InquilinosRepository repo = new();
        Inquilino inquilinoEncontrado = repo.GetInquilinoByDni(dni); // Tu lógica de búsqueda

        if (inquilinoEncontrado != null)
        {
            // Retorna el objeto Propietario como JSON
            return Ok(inquilinoEncontrado);
        }
        else
        {
            return NotFound();
        }
    }

    [HttpGet("api/Inmuebles/GetInquilinos")]
    public IActionResult GetAllInquilinos()
    {

        InquilinosRepository repo = new();
        List<Inquilino> inquilinos = repo.GetAllInquilinos();

        if (inquilinos.Count > 0)
        {
            // Retorna la lista de propietarios como JSON
            return Ok(inquilinos);
        }
        else
        {
            return NotFound();
        }
    }

    [HttpGet("Inquilinos/FiltrarInquilinos")]
    public IActionResult FiltrarInquilinos([FromQuery] string searchTerm)
    {

        IActionResult result = GetAllInquilinos();

        if (result is OkObjectResult okObjectResult)
        {
            var inquilinosResponse = okObjectResult.Value;
            if (inquilinosResponse is List<Inquilino> inquilino)
            {
                if (string.IsNullOrEmpty(searchTerm))
                {
                    return Json(inquilino);
                }

                var inquilinosFiltrados = inquilino.Where(p =>
                    p.Nombre.Contains(searchTerm, System.StringComparison.OrdinalIgnoreCase) ||
                    p.Apellido.Contains(searchTerm, System.StringComparison.OrdinalIgnoreCase) ||
                    p.Dni.Contains(searchTerm, System.StringComparison.OrdinalIgnoreCase)
                ).ToList();

                return Json(inquilinosFiltrados);
            }
        }
        return BadRequest("Error al obtener los inquilinos");
    }

}

Controllers/UsuariosController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Inmobiliaria.Models;
using Microsoft.AspNetCore.Authorization;
namespace Inmobiliaria.Controllers;

[Authorize]

public class UsuariosController : Controller
{
    private readonly ILogger<UsuariosController> _logger;
    private UsuariosRepository _repo;
    private readonly IConfiguration configuration;
    private readonly IWebHostEnvironment environment;

    public UsuariosController(ILogger<UsuariosController> logger, IConfiguration configuration, IWebHostEnvironment enviroment)
    {
        _repo = new UsuariosRepository();
        this.configuration = configuration;
        this.environment = enviroment;
        _logger = logger;
    }
    [Authorize(Policy = "Administrador")]
    public IActionResult Index()
    {
        List<Usuario> users = _repo.GetAllUsuarios();
        return View(users);
    }

    [AllowAnonymous]
    public IActionResult Login()
    {

        return View();
    }

    [HttpPost]
    [AllowAnonymous]
    public async Task<IActionResult> Login(Login login)

    {
        Console.WriteLine("ENTRO LOGIN");
        try
        {
            Console.WriteLine("ENTRO LOGIN");
            if (ModelState.IsValid)
            {

                string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                    password: login.Clave,
                    salt: System.Text.Encoding.ASCII.GetBytes(configuration["Salt"]),
                    prf: KeyDerivationPrf.HMACSHA1,
                    iterationCount: 1000,
                    numBytesRequested: 256 / 8
                ));
                var r = _repo.GetUserByMail(login.Correo);
                Console.WriteLine(r);
                if (r == null || r.Clave != hashed)
                {
                    TempData["AlertMessage"] = "Usuario o contraseña incorrectos";
                    TempData["AlertType"] = "error";
                    return View("Login");
                }
                var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, r.Correo),
                        new Claim(ClaimTypes.Role, r.Rol.ToString())
                    };
                var claimsIdentity = new ClaimsIdentity(
                    claims, CookieAuthenticationDefaults.AuthenticationScheme
                );
                await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimsIdentity));
                return Redirect("/Home");
            }
            return View();
        }
        catch (Exception ex)
        {
            ModelState.AddModelError("", ex.Message);
            return View();
        }
    }


    [AllowAnonymous]
    public async Task<ActionResult> Logout()
    {
        await HttpContext.SignOutAsync(
            CookieAuthenticationDefaults.AuthenticationScheme
        );
        return RedirectToAction("Index", "Home");
    }

    [Authorize(Policy = "Administrador")]
    public IActionResult Create()
    {
        UsuariosRepository repo = new();
        var roles = repo.getEnumRol();
        ViewBag.roles = roles;
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Policy = "Administrador")]
    public ActionResult Create(Usuario usuario, string ClaveNuevamente)
    {
        try
        {
            string returnUrl = Request.Headers["Referer"].ToString();
            Uri refererUri = new Uri(returnUrl);
            string relativePath = refererUri.GetComponents(UriComponents.PathAndQuery, UriFormat.SafeUnescaped);
            if (ClaveNuevamente != usuario.Clave)
            {

                TempData["AlertMessage"] = "Las contraseñas no coinciden";
                TempData["AlertType"] = "error";
                return RedirectToAction("Create");
            }

            string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                        password: usuario.Clave,
                        salt: System.Text.Encoding.ASCII.GetBytes(configuration["Salt"]),
                        prf: KeyDerivationPrf.HMACSHA1,
                        iterationCount: 1000,
                        numBytesRequested: 256 / 8
                    ));
            usuario.Clave = hashed;

            var res = _repo.CreateUsuario(usuario);
            if (res == -2)
            {

                TempData["AlertMessage"] = "Ya existe una cuenta registrada con ese email.";
                TempData["AlertType"] = "error";
                return RedirectToAction("Create");

            }
            if (res == -3)
            {
                TempData["AlertMessage"] = "Ya existe una cuenta registrada con ese Dni.";
                TempData["AlertType"] = "error";
                return RedirectToAction("Create");
            }
            if (usuario.AvatarFile != null && usuario.Id > 0)
            {
                string wwwPath = environment.WebRootPath;
                string path = Path.Combine(wwwPath, "Uploads");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                string fileName = "avatar_" + usuario.Id + Path.GetExtension(usuario.AvatarFile.FileName);
                string pathCompleto = Path.Combine(path, fileName);
                usuario.Avatar = Path.Combine("/Uploads", fileName);
                using (FileStream stream = new FileStream(pathCompleto, FileMode.Create))
                {
                    usuario.AvatarFile.CopyTo(stream);
                }
                _repo.UpdateAvatar(usuario);

            }

            TempData["AlertMessage"] = "Usuario creado correctamente";
            TempData["AlertType"] = "success";
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            throw;
        }
    }

    public ActionResult Perfil()
    {
        UsuariosRepository repo = new();
        var roles = repo.getEnumRol();
        ViewBag.roles = roles;
        ViewBag.Titulo = "Mi Perfil";
        var u = _repo.GetUserByMail(User.Identity.Name);
        return View("Update", u);
    }

    [Authorize(Policy = "Administrador")]
    public ActionResult Update(int id)
    {
        UsuariosRepository repo = new();
        var roles = repo.getEnumRol();
        ViewBag.roles = roles;
        ViewBag.Titulo = "Modificar Usuario";
        var usuario = _repo.GetUserById(id);
        return View(usuario);
    }

    // [HttpPost]

    // public ActionResult Update(Usuario usuario, string ClaveActual, string ClaveNueva)
    // {
    //     var usuarioAnt = _repo.GetUserById(usuario.Id);

    //     var claveActual = Convert.ToBase64String(KeyDerivation.Pbkdf2(
    //                     password: ClaveActual,
    //                     salt: System.Text.Encoding.ASCII.GetBytes(configuration["Salt"]),
    //                     prf: KeyDerivationPrf.HMACSHA1,
    //                     iterationCount: 1000,
    //                     numBytesRequested: 256 / 8
    //                 ));
    //     Console.WriteLine("ClaveActual: " + claveActual);
    //     Console.WriteLine("ClaveAnterior: " + usuarioAnt.Clave);


    //     try
    //     {
    //         if (ClaveNueva == null || ClaveNueva == "")
    //         {
    //             usuario.Clave = usuarioAnt.Clave;
    //         }
    //         else
    //         {

    //             {
    //                 if (claveActual == usuarioAnt.Clave)
    //                 {
    //                     Console.WriteLine("ENTROOOOO");
    //                     string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
    //                    password: ClaveNueva,
    //                    salt: System.Text.Encoding.ASCII.GetBytes(configuration["Salt"]),
    //                    prf: KeyDerivationPrf.HMACSHA1,
    //                    iterationCount: 1000,
    //                    numBytesRequested: 256 / 8
    //                ));
    //                     usuario.Clave = hashed;
    //                 }
    //                 else
    //                 {
    //                     usuario.Clave = usuarioAnt.Clave;
    //                     TempData["AlertMessage"] = "La contraseña actual es incorrecta";
    //                     TempData["AlertType"] = "error";
    //                 }


    //             }


    //         }

    //         if (usuario.AvatarFile != null)
    //         {
    //             string wwwPath = environment.WebRootPath;
    //             string path = Path.Combine(wwwPath, "Uploads");
    //             if (!Directory.Exists(path))
    //             {
    //                 Directory.CreateDirectory(path);
    //             }
    //             string fileName = "avatar_" + usuario.Id + Path.GetExtension(usuario.AvatarFile.FileName);
    //             string pathCompleto = Path.Combine(path, fileName);
    //             usuario.Avatar = Path.Combine("/Uploads", fileName);
    //             using (FileStream stream = new FileStream(pathCompleto, FileMode.Create))
    //             {
    //                 usuario.AvatarFile.CopyTo(stream);
    //             }
    //         }
    //         else
    //         {
    //             usuario.Avatar = usuarioAnt.Avatar;
    //         }

    //         if (!User.IsInRole("Administrador"))
    //         {
    //             //vista = nameof(Perfil);
    //             var usuarioActual = _repo.GetUserByMail(User.Identity.Name);
    //             if (usuarioActual.Id != usuario.Id)
    //             {
    //                 return RedirectToAction(nameof(Index));
    //             }
    //         }
    //         var res = _repo.UpdateUsuario(usuario);

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark"  >
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inmobiliaria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sweetalert2.dark.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Inmobiliaria.styles.css" asp-append-version="true" /> 
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" /> 
   

    
</head>
<body class="text-success">
    <header class="mb-5">
        <nav
          class="navbar navbar-expand-lg bg-body-tertiary  rounded col-md-9 mx-auto mt-4"
          aria-label="Thirteenth navbar example">
          <div class="container-fluid">
            <button
              class="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarsExample11"
              aria-controls="navbarsExample11"
              aria-expanded="false"
              aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse d-lg-flex p-0" id="navbarsExample11">
              <a class="navbar-brand col-lg-3 me-0 p-0 my-1" href="/"><img src="~/content/logo.png" class="img-logo" alt="" srcset=""></a>
              <ul class="navbar-nav col-lg-6 justify-content-lg-center">
                <li class="nav-item">
                  <a class="nav-link " aria-current="page" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-house"></i> Home    </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " aria-current="page" asp-controller="Inquilinos" asp-action="Index"><i class="fa-solid fa-person"></i> Inquilinos</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " aria-current="page" asp-controller="Propietarios" asp-action="Index"><i class="fa-solid fa-person-shelter"></i> Propietarios</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " aria-current="page" asp-controller="Inmuebles" asp-action="Index"><i class="fa-solid fa-building"></i> Inmuebles</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " aria-current="page" asp-controller="Contratos" asp-action="Index"><i class="fa-solid fa-file-signature"></i> Contratos</a>
                </li>
                @if(User.IsInRole("Administrador"))
                  {
                      <li class="nav-item">
                          <a class="nav-link "  asp-controller="Usuarios" asp-action="Index"><i class="fa-solid fa-user-tie"></i> Usuarios</a>
                      </li>
                  }
                
                
              </ul>
              <div class="d-lg-flex col-lg-3 justify-content-lg-end">
                
                @if(User.Identity.IsAuthenticated){
                  <div class="dropdown d-flex ">
                    <a class="btn btn-outline-light dropdown-toggle my-auto" style="height:fit-content;" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                      @User.Identity.Name
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                      <li><a asp-controller="Usuarios" asp-action="Perfil" class="dropdown-item text-light " aria-current="page">Perfil</a></li>
                      <li><a class="dropdown-item " asp-controller="Usuarios" asp-action="Logout"><i class="fa-solid fa-right-to-bracket" style="transform: rotate(180deg);"></i> Logout </a> </li>
                      @* <li><form asp-controller="Usuarios" asp-action="Logout">
                          <button class="dropdown-item"><i class="fa-solid fa-right-to-bracket" style="transform: rotate(180deg);"></i> Logout </button>
                           </form>
                      </li> *@
                      
                    </ul>
                  </div>
                  
                  
                  
                
                }else{
                  <a href="/Usuarios/Login" class="btn btn-outline-light"><i class="fa-solid fa-right-to-bracket" style=""></i> Login</a>
                  
                }
                
                
                <p></p>
              </div>
            </div>
          </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Inmobiliaria - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="https://kit.fontawesome.com/a5eb905d06.js" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/color-modes.js" asp-append-version="true"></script>
    <script src="~/js/sweetalert2.all.min.js" asp-append-version="true"></script>
    <script src="~/js/alertas.js" asp-append-version="true"></script>


    
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>