Models/Contrato.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Inmobiliaria.Models;
[Table("contratos")]
public class Contrato
{
    [Required]
    public int Id { get; set; }
    [Required]
    public int IdInquilino { get; set; }
    [Required]
    public Inquilino? Inquilino { get; set; }
    [Required]
    public int IdInmueble { get; set; }
    [Required]
    public Inmueble? Inmueble { get; set; }
    [Required]
    public Double MontoMensual { get; set; }
    [Required]
    public DateTime FechaInicio { get; set; }
    [Required]
    public DateTime FechaFin { get; set; }
    [Required]
    public bool Estado { get; set; }

}

Models/Contratos.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Inmobiliaria.Models;
[Table("contratos")]
public class Contrato
{
    [Required]
    public int Id { get; set; }
    [Required]
    public int IdInquilino { get; set; }
    [Required]
    public Inquilino? Inquilino { get; set; }
    [Required]
    public int IdInmueble { get; set; }
    [Required]
    public Inmueble? Inmueble { get; set; }
    [Required]
    public Double MontoMensual { get; set; }
    [Required]
    public DateTime FechaInicio { get; set; }
    [Required]
    public DateTime FechaFin { get; set; }
    [Required]
    public bool Estado { get; set; }

}

Controllers/InmueblesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Inmobiliaria.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.VisualBasic;
namespace Inmobiliaria.Controllers;

[Authorize]
public class InmueblesController : Controller
{
    private readonly ILogger<InmueblesController> _logger;
    private readonly InmueblesRepository _repo=new();

    public InmueblesController(ILogger<InmueblesController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index(int id)
    {
        if (id == 0)
        {
            Console.WriteLine($"id: {id}");
            InmueblesRepository repo = new();
            List<Inmueble> inmueble = _repo.GetAllInmuebles();
            ViewBag.Disponibles = false;
            return View(inmueble);
        }
        else
        {

            return IndexInmueblesPropietario(id);
        }

    }
    public IActionResult IndexDisponibles(int id)
    {
        InmueblesRepository repo = new();
        List<Inmueble> inmueble = repo.GetAllInmueblesDisponibles();
        Console.WriteLine(inmueble[0]);
        ViewBag.Disponibles = true;
        return View("Index", inmueble);

    }
    public IActionResult IndexInmueblesPropietario(int id)
    {
        InmueblesRepository repo = new();
        PropietariosRepository repoPropietarios = new();
        ViewBag.NombrePropietario=repoPropietarios.GetPropietarioById(id).ToString();
       
        List<Inmueble> inmuebles = repo.GetInmueblesPropietario(id);
          

        return View("Index", inmuebles);
    }
    public IActionResult Create()
    {
        InmueblesRepository repo = new();
        var enumTipo = repo.getEnumTipos();
        var enumUso = repo.getEnumUso();
        ViewBag.enumTipo = enumTipo;
        ViewBag.enumUso = enumUso;
        return View();
    }

    [HttpPost]
    public IActionResult Create(Inmueble inmueble)
    {

        try
        {
            InmueblesRepository repo = new();

            var res = repo.CreateInmueble(inmueble);
            if (res > 0)
            {

                TempData["AlertMessage"] = "Inmueble creado correctamente.";
                TempData["AlertType"] = "success";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["AlertMessage"] = "No se pudo crear el inmueble.";
                TempData["AlertType"] = "error";
                return RedirectToAction("Create");
            }

        }
        catch (System.Exception)
        {
            throw;
        }

    }
    [HttpPost]
    public IActionResult PausarPlay(int id)
    {
        try
        {

            InmueblesRepository repo = new();
            Inmueble inmueble = repo.GetInmuebleById(id);
            string returnUrl = Request.Headers["Referer"].ToString();
            Uri refererUri = new Uri(returnUrl);
            string relativePath = refererUri.GetComponents(UriComponents.PathAndQuery, UriFormat.SafeUnescaped);

            if (inmueble.Disponible)
            {
                inmueble.Disponible = false;
                TempData["AlertMessage"] = "El Inmueble se pauso correctamente.";
                TempData["AlertType"] = "success";
            }
            else
            {
                inmueble.Disponible = true;
                TempData["AlertMessage"] = "El Inmueble se encuentra disponible nuevamente.";
                TempData["AlertType"] = "success";
            }
            repo.UpdateInmuebleDisponible(inmueble);

            return Redirect(relativePath);
        }
        catch (System.Exception)
        {
            throw;
        }

    }

    [HttpPost]
    [Authorize(Policy = "Administrador")]
    public IActionResult Delete(int id)
    {
        string returnUrl = Request.Headers["Referer"].ToString();
        Uri refererUri = new Uri(returnUrl);
        string relativePath = refererUri.GetComponents(UriComponents.PathAndQuery, UriFormat.SafeUnescaped);
        try
        {
            InmueblesRepository repo = new();
            repo.DeleteInmueble(id);
            return Redirect(relativePath);
        }
        catch (System.Exception)
        {
            throw;
        }
    }
    public IActionResult Update(int id)
    {
        InmueblesRepository repo = new();
        var inmueble = repo.GetInmuebleById(id);
        var enumTipo = repo.getEnumTipos();
        var enumUso = repo.getEnumUso();
        TempData["RefererUrl"] = Request.Headers["Referer"].ToString();
        ViewBag.enumTipo = enumTipo;
        ViewBag.enumUso = enumUso;
        return View(inmueble);
    }

    [HttpPost]
    public IActionResult Update(Inmueble inmueble)
    {
        InmueblesRepository repo = new();
        Console.WriteLine(inmueble.ToString());
        string? returnUrl = TempData["RefererUrl"]?.ToString();
        int res = repo.UpdateInmueble(inmueble);
        if (res > 0)
        {

            TempData["AlertMessage"] = "Inmueble modificado correctamente.";
            TempData["AlertType"] = "success";
            if (!string.IsNullOrEmpty(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                // Maneja el caso en el que no haya URL de referencia
                return RedirectToAction("Index");
            }
        }
        else
        {
            TempData["AlertMessage"] = "No se pudo modificar el inmueble.";
            TempData["AlertType"] = "error";
            return RedirectToAction("Update");
        }

    }

    public IActionResult Details(int id)
    {
        InmueblesRepository repo = new();
        var propietario = repo.GetInmuebleById(id);
        return View(propietario);
    }

    [HttpGet("api/Inmuebles/GetInmueble/{id}")]
    public IActionResult GetInmueble(int id)
    {
        // Aquí, realiza la lógica para buscar el propietario por DNI
        InmueblesRepository repo = new();
        Inmueble inmuebleEncontrado = repo.GetInmuebleById(id); // Tu lógica de búsqueda

        if (inmuebleEncontrado != null)
        {
            // Retorna el objeto Propietario como JSON
            return Ok(inmuebleEncontrado);
        }
        else
        {
            return NotFound();
        }
    }

    // [HttpGet("api/Inmuebles/GetInmuebles")]
    // public IActionResult GetAllInmuebles()
    // {

    //     InmueblesRepository repo = new();
    //     List<Inmueble> inmuebles = repo.GetAllInmuebles();
    //     Console.WriteLine(inmuebles[1].ToString());

    //     if (inmuebles.Count > 0)
    //     {

    //         return Ok(inmuebles);
    //     }
    //     else
    //     {
    //         return NotFound();
    //     }
    // }

    [HttpGet("Inmuebles/FiltrarInmuebles")]
    public IActionResult FiltrarInmuebles([FromQuery] string searchTerm,[FromQuery] DateTime fechaInicio, [FromQuery] DateTime fechaFin)
    {
        Console.WriteLine("ENTRO");
        IActionResult result = Ok(_repo.GetAllInmueblesFecha(fechaInicio, fechaFin));
        // Obtener el resultado

        if (result is OkObjectResult okObjectResult)
        {
            var inmueblesResponse = okObjectResult.Value; // Obtener el contenido del resultado
            if (inmueblesResponse is List<Inmueble> inmuebles)
            {
                if (string.IsNullOrEmpty(searchTerm))
                {
                    var inmueblesActivos = inmuebles.Where(i => i.Estado == true &&
                    i.Disponible == true).ToList();
                    return Json(inmueblesActivos); // Retorna los inmuebles activos si no hay término de búsqueda
                }

                // Filtra los inmuebles activos por el término de búsqueda (puedes personalizar la lógica según tus necesidades)
                var inmueblesFiltrados = inmuebles.Where(i =>
                    i.Estado == true &&
                    i.Disponible == true &&
                    (i.Propietario.Nombre.Contains(searchTerm, StringComparison.OrdinalIgnoreCase) ||
                     i.Propietario.Apellido.Contains(searchTerm, StringComparison.OrdinalIgnoreCase) ||
                     i.Propietario.Dni.Contains(searchTerm, StringComparison.OrdinalIgnoreCase) ||
                     i.Direccion.Contains(searchTerm, StringComparison.OrdinalIgnoreCase)
                     || i.Tipo.ToString().Contains(searchTerm, StringComparison.OrdinalIgnoreCase)

                    )
                ).ToList();

                // var propiedades = typeof(Inmueble).GetProperties();

                // foreach (var propiedad in propiedades)
                // {
                //     var nombrePropiedad = propiedad.Name;
                //     var valorPropiedad = propiedad.GetValue(inmueblesFiltrados);

                //     Console.WriteLine($"{nombrePropiedad}: {valorPropiedad}");
                // }
                return Json(inmueblesFiltrados);
            }
        }

        // Si algo salió mal o el tipo no coincide, regresa un error u otra respuesta
        return BadRequest("Error al obtener los inmuebles");
    }



}

Controllers/PagosController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Inmobiliaria.Models;
using Microsoft.AspNetCore.Authorization;
namespace Inmobiliaria.Controllers;
[Authorize]
public class PagosController : Controller
{
    private readonly ILogger<PagosController> _logger;

    public PagosController(ILogger<PagosController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index(int id)
    {    
        PagosRepository repo = new();
        ContratosRepository repoContrato = new();
        ViewBag.Contrato = repoContrato.GetContratoById(id); 
        List<Pago> pagos = repo.GetPagoByContratoId(id);    
        TempData["IdContrato"] = id;
        if (pagos.Count > 0)
        {
            return View(pagos);
        }
        else
        {
            return View();
        }

    }
    // public IActionResult Index2(int id)
    // {
    //     PagosRepository repo = new();
    //     ContratosRepository repoContrato = new();
    //     ViewBag.Contrato = repoContrato.GetContratoById(id);
    //     List<Pago> pagos = repo.GetPagoByContratoId(id);
    //     ViewBag.LinkBack="/Contratos/FiltrarPorInmueble/"+pagos[0].Contrato.IdInmueble;
    //     TempData["IdContrato"] = id;
    //     if (pagos.Count > 0)
    //     {
    //         return View("Index",pagos);
    //     }
    //     else
    //     {
    //         return View("Index");
    //     }

    // }
    public IActionResult Create(int IdContrato)
    {
        ContratosRepository repo = new();
        Contrato contrato = repo.GetContratoById(IdContrato);
        return View(contrato);
    }



    [HttpPost]
    public IActionResult Create(Pago pago)
    {
        try
        {
            PagosRepository repo = new();
            var res = repo.CreatePago(pago);
            ContratosRepository repoContrato = new();
            ViewBag.Contrato = repoContrato.GetContratoById(pago.IdContrato);

            string returnUrl = $"/Pagos/Index/{pago.IdContrato}";

            if (res > 0)
            {
                TempData["AlertMessage"] = "Contrato creado correctamente.";
                TempData["AlertType"] = "success";
            }
            else
            {
                TempData["AlertMessage"] = "No se pudo generar el pago, debido a un error en el sistema.";
                TempData["AlertType"] = "error";
            }

            // Redireccionar a la página de Index de Pagos con el parámetro IdContrato
            return Redirect(returnUrl);
        }
        catch (System.Exception)
        {
            throw;
        }
    }


    [HttpPost]
    [Authorize(Policy = "Administrador")]
    public IActionResult Delete(int id)
    {
        try
        {
            PagosRepository repo = new();
            repo.DeletePago(id);
            string returnUrl = Request.Headers["Referer"].ToString();
            Uri refererUri = new Uri(returnUrl);
            string relativePath = refererUri.GetComponents(UriComponents.PathAndQuery, UriFormat.SafeUnescaped);
            return Redirect(relativePath);
        }
        catch (System.Exception)
        {
            throw;
        }
    }
    public IActionResult Update(int id)
    {
        PagosRepository repo = new();
        ContratosRepository repoContrato = new();
        var pago = repo.GetPagoById(id);
        Contrato contrato = repoContrato.GetContratoById(pago.IdContrato);
        pago.Contrato = contrato;


        return View(pago);
    }

    [HttpPost]
    public IActionResult Update(Pago pago)
    {
        try
        {
            PagosRepository repo = new();
            var res = repo.UpdatePago(pago);
            ContratosRepository repoContrato = new();
            ViewBag.Contrato = repoContrato.GetContratoById(pago.IdContrato);

            string returnUrl = $"/Pagos/Index/{pago.IdContrato}";

            if (res > 0)
            {
                TempData["AlertMessage"] = "Contrato modificado correctamente.";
                TempData["AlertType"] = "success";
            }
            else
            {
                TempData["AlertMessage"] = "No se pudo modificar el pago, debido a un error en el sistema.";
                TempData["AlertType"] = "error";
            }

            // Redireccionar a la página de Index de Pagos con el parámetro IdContrato
            return Redirect(returnUrl);
        }
        catch (System.Exception)
        {
            throw;
        }

    }

    public IActionResult Details(int id)
    {
        PagosRepository repo = new();
        ContratosRepository repoContrato = new();
        var contrato = repo.GetPagoById(id);
        contrato.Contrato = repoContrato.GetContratoById(contrato.IdContrato);
        return View(contrato);
    }


}

Views/Contratos/Details.cshtml
@model Inmobiliaria.Models.Contrato

@{
  ViewData["Title"] = "Detalles Contrato";
}

<div class="text-center">
  <div class="text-center">
    <h1 class="display-4 mb-5">Detalles del Contrato</h1>
    <div class="container mt-4">
      <div class="card mx-auto col-md-8">
        <div class="card-body">
          <div class="form-group mt-3 d-flex justify-content-center gap-5">

            <div>
              <button id="Contrato" type="button"
                class="btn btn-success d-flex justify-content-center align-items-center btn-lg"
                style="width: fit-content;height: fit-content;" title="Renovar" data-bs-toggle="modal"
                data-bs-target="#modalRenovarContrato">
                <i class="fa-solid fa-file-circle-plus"></i>&nbsp;Renovar Contrato
              </button>
            </div>
          </div>
          <h3 class="mt-3">Datos del Contrato</h3>
          <input value="@Model.Id" name="IdContratoV" type="hidden" />
          <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text- *center">
            <input value="@Model.FechaInicio.ToString("dd-MM-yyyy")" class="form-control input-top" type="text"
              id="fechaInicioV" placeholder="asd" disabled>
            <label for="fechaInicio" class="ms-2">Fecha de Inicio</label>
          </div>
          <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto text- *center">
            <input value=@Model.FechaFin.ToString("dd-MM-yyyy") class="form-control input-mid" type="text"
              id="fechaFinV" placeholder="asd" disabled>
            <label for="fechaFin" class="ms-2">Fecha de Finalizacion</label>
          </div>
          <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto text- *center">
            <input value="$@Model.MontoMensual" class="form-control input-mid" type="text" id="montoMensualV"
              placeholder="asd" disabled>
            <label for="montoMensual" class="ms-2">Monto Mensual</label>
          </div>
          <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text- *center">
            <input value=@(Model.Estado ? "Activo" : "Inactivo") class="form-control input-bot" type="text" id="estadoV"
              placeholder="asd" disabled>
            <label for="estado" class="ms-2">Estado</label>
          </div>

          <h3 class="mt-3">Datos del Inquilino</h3>
          <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text- *center">
            <input value="@Model.Inquilino.Apellido" class="form-control input-top" type="text" id="ApellidoV"
              placeholder="asd" disabled />
            <label for="apellido" class="ms-2">Apellido</label>
          </div>

          <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
            <input value="@Model.Inquilino.Nombre" class="form-control input-mid" type="text" id="NombreV"
              placeholder="asd" disabled />
            <label for="nombre" class="ms-2">Nombre</label>
          </div>

          <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
            <input value="@Model.Inquilino.Dni" class="form-control input-mid" type="text" id="DniV" placeholder="asd"
              disabled />
            <label for="dni" class="ms-2">DNI <span class="fs-7">(formato: XX.XXX.XXX)</span></label>
          </div>

          <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
            <input value="@Model.Inquilino.Telefono" class="form-control input-mid" type="tel" id="TelefonoV"
              placeholder="asd" disabled />
            <label for="telefono" class="ms-2">Teléfono <span class="fs-7">(Formato +XX XXX-XXXXXXX)</span></label>
          </div>

          <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
            <input value="@Model.Inquilino.Correo" class="form-control input-bot" type="email" id="CorreoV"
              placeholder="asd" disabled />
            <label for="correo" class="ms-2">Correo</label>
          </div>
          <input id="idInquilinoV" type="hidden" value=@Model.Inquilino.Id>

          <h3 class="mt-3">Datos del Inmueble</h3>
          <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
            <input value="@Model.Inmueble.Direccion" class="form-control input-top" type="text" id="DireccionV"
              disabled />
            <label for="direccion" class="ms-2">Dirección</label>
          </div>

          <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto text-center">
            <input value="@Model.Inmueble.Uso" class="form-control input-mid" type="text" id="UsoV" disabled />
            <label for="uso" class="ms-2">Uso</label>
          </div>

          <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
            <input value="@Model.Inmueble.Tipo" class="form-control input-mid" type="text" id="TipoV" disabled />
            <label for="tipo" class="ms-2">Tipo</label>
          </div>

          <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto text-center">
            <input value="@Model.Inmueble.CantAmbientes" class="form-control input-mid" type="number"
              id="CantAmbientesV" disabled />
            <label for="cantAmbientes" class="ms-2">Cantidad de Ambientes</label>
          </div>

          <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
            <input value="@Model.Inmueble.Latitud" class="form-control input-mid" type="text" id="LatitudV" step="any"
              disabled />
            <label for="latitud" class="ms-2">Latitud</label>
          </div>

          <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
            <input value="@Model.Inmueble.Longitud" class="form-control input-mid" type="text" id="LongitudV" step="any"
              disabled />
            <label for="longitud" class="ms-2">Longitud</label>
          </div>



          <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
            <input id="precio" value="$ @Model.Inmueble.Precio" class="form-control input-mid" type="text" id="PrecioV"
              step="any" disabled />
            <label for="precio" class="ms-2">Precio</label>
          </div>

          <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
            <input value="@Model.Inmueble.Propietario.ToString()" class="form-control input-bot" type="text"
              id="PropietarioV" step="any" disabled />
            <label class="ms-2">Propietario</label>
          </div>
          <input id="idInmuebleV" type="hidden" value=@Model.Inmueble.Id>

          <div class="modal fade" id="modalRenovarContrato">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title mx-auto" id="exampleModalLabel">Renovar Contrato</h5>

                </div>
                <div class="modal-body">
                  <div id="modal-content">
                    @Html.Partial("_Renovar", Model)

                  </div>
                </div>


                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                </div>

              </div>
            </div>

          </div>


        </div>
      </div>
    </div>

   
    
    <div class="form-group mt-3">
      <button type="button" class="btn btn-primary mx-auto" style="width: fit-content" onclick="window.history.back()">
        <i class="fa-solid fa-circle-left"></i>
      </button>
    </div>
  </div>
</div>


@* <script src="~/js/modalRenovarContrato.js" asp-append-version="true"></script> *@

Views/Contratos/Index.cshtml
@model List<Inmobiliaria.Models.Contrato>

@{
    ViewData["Title"] = "Contratos";
}

<div class="text-center">
    <h1 class="display-4 mb-5">Contratos</h1>
    @if (TempData["Multa"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            El Inquilino <strong>@TempData["Inquilino"]</strong> debera abonar una multa de
            <strong>@TempData["Multa"]</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }

    <table class="table table-striped table-dark table-hover">
        <div class="row d-flex justify-content-between mb-3">
            <div class="col d-flex justify-content-start gap-3 align-items-center ">
                <h5 class="position-relative">Detalle de los Contratos</h5>
                @if (ViewBag.Disponibles != null)
                {
                    @if (ViewBag.Disponibles)
                    {
                        <a asp-action="Index" class="btn btn-outline-warning ">Mostrar Todos</a>
                        <form asp-action="FiltrarPorFecha" class="d-flex justify-content-start">
                            <div id="desdeContainer"
                                class="d-flex gap-2 justify-content align-items-center   text-center ">
                                <label for="Desde" >Desde</label>
                                <input id="desde" class="form-control" type="date" name="Desde" placeholder="sad"
                                    required
                                    onchange="document.getElementById('hasta').min = document.getElementById('desde').value">
                                
                            </div>

                            <div id="hastaContainer"
                                class="d-flex gap-2  justify-content align-items-center  text-center ">
                                <label for="Hasta" >Hasta</label>
                                <input id="hasta" class="form-control" type="date" name="Hasta" placeholder="sad"
                                    required>   
                            </div>
                            <button class="btn btn-outline-primary"><i class="fa-solid fa-calendar-days"></i></button>
                        </form>
                    }
                    else if (!ViewBag.Disponibles)
                    {
                        <a asp-action="IndexDisponibles" class="btn btn-outline-warning ">Mostrar Vigentes</a>
                    }
                }
            </div>
             @if (ViewBag.Disponibles != null)
            {
               <div class="col-1 d-flex justify-content-end">
                <a href="/Contratos/Create" class="btn btn-success " title="Crear"> <i
                        class="fa-solid fa-circle-plus "></i></a>
            </div>

            }
            


        </div>
        <thead>
            <tr>

                <th>Inquilino</th>
                <th>Inmueble N°/Direccion</th>
                <th>Monto Mensual</th>
                <th>Fecha de Inicio</th>
                <th>Fecha Fin</th>
                @* <th>Estado</th> *@
                <th>Acciones</th>
            </tr>

        </thead>
        @if (Model.Count > 0)
        {
        <tbody>
            @foreach (var Contrato in Model)
            {

                <tr>

                    <td>@Contrato.Inquilino.ToString()</td>
                    <td>@Contrato.Inmueble.Id - @Contrato.Inmueble.Direccion </td>
                    <td>$@Contrato.MontoMensual</td>
                    <td>@Contrato.FechaInicio.ToString("dd-MM-yyyy")</td>
                    <td>@Contrato.FechaFin.ToString("dd-MM-yyyy")</td>
                    @* <td><i class="fa-solid fa-circle @(Contrato.Estado==true?"text-success":"text-danger")"></i></td> *@



                    <td class="d-flex gap-2 justify-content-center align-items-center">
                        @if (User.IsInRole("Administrador"))
                        {
                            <form id="formBorrar_@Contrato.Id" asp-action="Delete" asp-route-id="@Contrato.Id"
                                onsubmit="return mostrarAlertaConSelect(event, 'formBorrar_@Contrato.Id')">
                                <button type="submit"
                                    class="btn btn-outline-danger w-75 h-75 d-flex justify-content-center align-items-center"
                                    title="Eliminar">
                                    <i class="fa-solid fa-trash"></i>
                                </button>
                            </form>
                        }

                        <div>
                            <a asp-controller="Contratos" asp-action="Update" asp-route-id="@Contrato.Id"
                                class="btn btn-outline-primary w-75  d-flex justify-content-center align-items-center"
                                title="Modificar"> <i class="fa-solid fa-pen-to-square" style="cursor:pointer;"></i> </a>
                        </div>
                        <div>
                            <a asp-controller="Contratos" asp-action="Details" asp-route-id="@Contrato.Id"
                                class="btn btn-outline-info w-75  d-flex justify-content-center align-items-center"
                                title="Detalles"> <i class="fa-solid fa-eye style=" cursor:pointer;""></i> </a>
                        </div>
                        <div>
                            <a asp-controller="Pagos" asp-action="Index" asp-route-id="@Contrato.Id"
                                class="btn btn-outline-warning w-75  d-flex justify-content-center align-items-center"
                                title="Pagos"> <i class="fa-solid fa-file-invoice-dollar" style="cursor:pointer;"></i></a>
                        </div>
                    </td>

                </tr>
            }
        </tbody>
         }else
        {
            <tbody>
                <tr>
                    <td colspan="9" class="text-center">No se encontraron contratos para este inmueble</td>
                </tr>
            </tbody>
        }
    </table>
    @if (ViewBag.Disponibles == null)
    {
        <div class="form-group mt-3">
            
               <a asp-action="Index" asp-controller="Inmuebles" 
               class="btn btn-primary mx-auto"><i class="fa-solid fa-circle-left"></i>
               </a>
        </div>
    }
</div>


<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    @if (TempData.ContainsKey("AlertMessage") && TempData.ContainsKey("AlertType"))
    {
        var alertMessage = TempData["AlertMessage"];
        var alertType = TempData["AlertType"];
        <text>
                Swal.fire({
                    icon: '@alertType',
                title: '@alertMessage',
                showConfirmButton: false,
                timer: 2000
                               // Mostrar durante 2 segundos
                          });
        </text>
    }
</script>