Models/Inmueble.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace Inmobiliaria.Models;
[Table("inmuebles")]
public class Inmueble
{
    [Required]
    public int Id { get; set; }
    [Required]
    public int IdPropietario { get; set; }
    [ForeignKey(nameof(IdPropietario))]
    public Propietario? Propietario { get; set; }
    [Required]
    public string Direccion { get; set; } = "";
    [Required]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public EnumUso Uso { get; set; }
    [Required]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public EnumTipo Tipo { get; set; }
    [Required]
    public int CantAmbientes { get; set; }
    [Required]
    public double Latitud { get; set; }
    [Required]
    public double Longitud { get; set; }
    [Required]
    public double Precio { get; set; }
    [Required]
    public bool Estado { get; set; } = true;
    [Required]
    public bool Disponible { get; set; } = true;

    public override string ToString()
    {
        return "USO: " + Uso + " ----- TIPO: " + Tipo;
    }

}

public enum EnumUso
{
    Comercial,
    Personal,

}

public enum EnumTipo
{
    Local,
    Deposito,
    Casa,
    Departamento


}

Controllers/ContratosController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Inmobiliaria.Models;
using Microsoft.AspNetCore.Authorization;

namespace Inmobiliaria.Controllers;
[Authorize]
public class ContratosController : Controller
{
    private readonly ILogger<ContratosController> _logger;

    public ContratosController(ILogger<ContratosController> logger)
    {
        _logger = logger;
    }


    public IActionResult Index()
    {
        ContratosRepository repo = new();
    
        List<Contrato> contratos = repo.GetAllContratos(false);
        ViewBag.Disponibles = false;
        return View(contratos);
    }

 
    public IActionResult IndexDisponibles()
    {
        ContratosRepository repo = new();
        List<Contrato> contratos = repo.GetAllContratos(true);
        ViewBag.Disponibles = true;
        return View("Index", contratos);

    }
    public IActionResult FiltrarPorFecha(DateTime Desde, DateTime Hasta)
    {
        ContratosRepository repo = new();
        List<Contrato> contratos = repo.GetAllContratosFecha(Desde, Hasta);
        ViewBag.Disponibles = true;
        return View("Index", contratos);

    }
    public IActionResult FiltrarPorInmueble(int id)
    {
        ContratosRepository repo = new();
        InmueblesRepository repoInmuebles=new();
        List<Contrato> contratos = repo.GetAllContratosInmueble(id);
        ViewBag.idPropietario=repoInmuebles.GetInmuebleById(id).IdPropietario;
        
        return View("Index", contratos);

    }
    public IActionResult Create()
    {
        return View();
    }



    [HttpPost]
    public IActionResult Create(Contrato contrato)
    {
        try
        {
            ContratosRepository repo = new();
            var res = repo.CreateContrato(contrato);
            if (res > 0)
            {

                TempData["AlertMessage"] = "Contrato creado correctamente.";
                TempData["AlertType"] = "success";
                return RedirectToAction("Index");
            }
            else if (res == -1)
            {
                TempData["AlertMessage"] = "No se pudo crear el Contrato, debido a un error en los datos ingresados";
                TempData["AlertType"] = "error";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["AlertMessage"] = "No se pudo crear el Contrato, Ya existe uno para ese inmueble en la fecha seleccionada.";
                TempData["AlertType"] = "error";
                return RedirectToAction("Index");
            }

        }
        catch (System.Exception)
        {
            throw;
        }

    }

    [HttpPost]
    [Authorize(Policy = "Administrador")]
    public IActionResult Delete(int id, string resignacion)
    {
        try
        {
            ContratosRepository repo = new();
            InquilinosRepository repoInquilino = new();
            PagosRepository repoPago = new();
            string RefererUrl = Request.Headers["Referer"].ToString();

            if (string.IsNullOrWhiteSpace(resignacion))
            {
                var pagos = repoPago.GetPagoByContratoId(id);
                repo.DeleteContrato(id);
            }
            else
            {
                if (ContratoPagado(id))
                {
                    Contrato contrato = repo.GetContratoById(id);
                    if (contrato != null)
                    {

                        // Calcular la multa
                        ContratoPagado(contrato.Id);
                        DateTime fechaFin = contrato.FechaFin;
                        DateTime fechaHoy = DateTime.Now;
                        TimeSpan tiempoTranscurrido = fechaFin - fechaHoy;
                        double diasTranscurridos = tiempoTranscurrido.Days;
                        double mesesTranscurridos = Math.Round(diasTranscurridos / 30);
                        Console.WriteLine("MEses transcurridos: " + mesesTranscurridos);
                        double multa;

                        TempData["Inquilino"] = repoInquilino.GetInquilinoById(contrato.IdInquilino).ToString();
                        if (mesesTranscurridos >= 2)
                        {
                            multa = contrato.MontoMensual * 2;
                            TempData["Multa"] = "$" + multa;
                        }
                        else
                        {
                            multa = contrato.MontoMensual;
                            TempData["Multa"] = "$" + multa;
                        }

                        TempData["AlertMessage"] = $"Se resigno el contrato, el cliente debera abonar una multa de {TempData["Multa"]}";
                        TempData["AlertType"] = "warning";



                        contrato.FechaFin = fechaHoy;
                        repo.DeleteContrato(contrato.Id);
                        repo.UpdateContrato(contrato);
                    }
                    else
                    {
                        throw new Exception("Contrato no encontrado");
                    }
                }
                else
                {
                    TempData["AlertMessage"] = $"No se pudo cancelar el contrato, debido a que el contrato no esta pagado en su totalidad";
                    TempData["AlertType"] = "error";
                }

            }

            return Redirect(RefererUrl);
        }
        catch (Exception ex)
        {
            // Manejar la excepción de manera adecuada, como registrarla o mostrar un mensaje de error al usuario
            return RedirectToAction($"Error: {ex.Message}");
        }
    }

    public IActionResult Update(int id)
    {
        ContratosRepository repo = new();
        var contrato = repo.GetContratoById(id);
        TempData["RefererUrl"] = Request.Headers["Referer"].ToString();
        return View(contrato);
    }

    [HttpPost]
    public IActionResult Update(Contrato contrato)
    {
        ContratosRepository repo = new();
        string? returnUrl = TempData["RefererUrl"]?.ToString();
        int res = repo.UpdateContrato(contrato);
        if (res > 0)
        {

            TempData["AlertMessage"] = "Contrato modificado correctamente.";
            TempData["AlertType"] = "success";
            if (!string.IsNullOrEmpty(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                // Maneja el caso en el que no haya URL de referencia
                return RedirectToAction("Index");
            }
        }
        else if (res == -1)
        {
            TempData["AlertMessage"] = "No se pudo modificar el Contrato, debido a un error en los datos ingresados";
            TempData["AlertType"] = "error";
            return RedirectToAction("Update");
        }
        else
        {
            TempData["AlertMessage"] = "No se pudo modificar el Contrato, Ya existe uno para ese inmueble en la fecha seleccionada.";
            TempData["AlertType"] = "error";
            return RedirectToAction("Update");
        }

    }

    public IActionResult Details(int id)
    {
        ContratosRepository repo = new();
        var contrato = repo.GetContratoById(id);
        return View(contrato);
    }

    [HttpGet("api/Contratos/GetContratos")]
    public IActionResult GetAllContratos()
    {
        // Aquí, realiza la lógica para obtener todos los contratos
        ContratosRepository repo = new();
        List<Contrato> contrato = repo.GetAllContratos(true); // Tu lógica para obtener todos los contratos

        if (contrato.Count > 0)
        {
            // Retorna la lista de contrats como JSON
            return Ok(contrato);
        }
        else
        {
            return NotFound();
        }
    }

    [HttpGet("Contratos/FiltrarContratos")]
    public IActionResult FiltrarContratos([FromQuery] string searchTerm)
    {

        IActionResult result = GetAllContratos(); // Obtener el resultado

        if (result is OkObjectResult okObjectResult)
        {
            var contratosResponse = okObjectResult.Value; // Obtener el contenido del resultado
            if (contratosResponse is List<Contrato> contratos)
            {
                if (string.IsNullOrEmpty(searchTerm))
                {
                    return Json(contratos);
                }


                var contratosFiltrados = contratos.Where(c =>
                    c.Inquilino.Nombre.Contains(searchTerm, System.StringComparison.OrdinalIgnoreCase) ||
                    c.Inquilino.Apellido.Contains(searchTerm, System.StringComparison.OrdinalIgnoreCase) ||
                    c.Inquilino.Dni.Contains(searchTerm, System.StringComparison.OrdinalIgnoreCase) ||
                    c.Inmueble.Direccion.Contains(searchTerm, System.StringComparison.OrdinalIgnoreCase) ||
                    c.MontoMensual.ToString().Contains(searchTerm, StringComparison.OrdinalIgnoreCase)


                ).ToList();

                return Json(contratosFiltrados);
            }
        }

        // Si algo salió mal o el tipo no coincide, regresa un error u otra respuesta
        return BadRequest("Error al obtener los contratos");
    }
    private bool ContratoPagado(int id)
    {
        ContratosRepository repo = new();
        PagosRepository repoPagos = new();
        var contrato = repo.GetContratoById(id);
        DateTime fechaInicio = contrato.FechaInicio;
        DateTime fechaHoy = DateTime.Now;
        TimeSpan tiempoTranscurrido = fechaHoy - fechaInicio;
        double diasTranscurridos = tiempoTranscurrido.Days + 1;
        double mesesTranscurridos = Math.Round(diasTranscurridos / 30);
        double valorParcialContrato = contrato.MontoMensual * mesesTranscurridos;
        double totalPAgados = 0;
        List<Pago> pagos = repoPagos.GetPagoByContratoId(id);
        pagos.ForEach(pago => totalPAgados += pago.Importe);
        double resto = valorParcialContrato - totalPAgados;

Views/Inmuebles/Create.cshtml
@{
  ViewData["Title"] = "Registrar Inmueble";
}


<div class="text-center">
  <h1 class="display-4 mb-5">Registrar Inmueble</h1>
  <div class="container mt-4 text-light ">
    <form id="formInmueble" class="form form-floating d-flex flex-wrap flex-column gap-4" method="post"
      data-bs-theme="dark" onsubmit="return confirmarCreacion(event)">
      <h3>Datos del Propietario</h3>
      <div class="container">
        <div class="d-flex gap-3 form-floating justify-content align-items-center mx-auto col-md-8 text-center">
          <input id="busquedaDni" class="form-control" type="text" placeholder="Buscar por DNI" disabled required>
          <button id="btnBuscarModalTodos" type="button" class="btn btn-primary btn-lg fa-solid fa-folder-tree"
            data-bs-toggle="modal" data-bs-target="#myModal"></button>
          <button id="Propietario" type="button" class="btn btn-success btn-lg fa-solid fa-circle-plus "></button>
          <label for="Propietario" class="ms-2">Ingrese un propietario</label>
        </div>
        <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Propietarios</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <input type="text" id="buscarModal" class="form-control mb-3"
                  placeholder="Buscar por DNI, Nombre o Apellido">
                <div id="ajaxContent">

                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
              </div>
            </div>
          </div>
        </div>

        <div class="modal fade" id="modalCrearPropietario">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title mx-auto" id="exampleModalLabel">Crear Propietario</h5>

              </div>

              <div class="modal-body">

                <div id="modal-content"></div>
              </div>


              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
              </div>

            </div>
          </div>

        </div>

        <div id="cardProp" class="card col-md-8 mt-3 mx-auto d-none">
          <div class="card-header">
            Detalles del Propietario
          </div>
          <div class="card-body">
            <p class="card-text fw-bold">Nombre: <span class="fw-normal" id="propietarioNombre"></span></p>
            <p class="card-text fw-bold">Apellido: <span class="fw-normal" id="propietarioApellido"> </span></p>
            <p class="card-text fw-bold">Correo: <span class="fw-normal" id="propietarioCorreo"></span></p>
            <p class="card-text fw-bold">Telefono: <span class="fw-normal" id="propietarioTelefono"></span></p>
          </div>
        </div>
        <input id="idPropietario" class="form-control" type="hidden" name="IdPropietario" required>
      </div>

      <div id="formInputs" class="d-flex flex-wrap gap-3 flex-column col-md-12 d-none">
        <h3>Datos del Inmueble</h3>
        <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto col-md-8 text-center">
          <input id="direccion" class="form-control" type="text" name="Direccion" placeholder="sad" required />
          <label for="direccion" class="ms-2">Dirección</label>
        </div>

        <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto col-md-8 text-center">
          <select id="uso" class="form-select" name="Uso" required>
            @foreach (var uso in ViewBag.enumUso)
            {
              <option value="@uso">@uso</option>
            }
          </select>
          <label for="uso" class="ms-2">Uso</label>
        </div>
        <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto col-md-8 text-center">
          <select id="tipo" class="form-select" name="Tipo" required>
            @foreach (var tipo in ViewBag.enumTipo)
            {
              <option value="@tipo">@tipo</option>
            }
          </select>
          <label for="tipo" class="ms-2">Tipo</label>
        </div>

        <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto col-md-8 text-center">
          <input id="cantAmbientes" class="form-control" type="number" name="CantAmbientes" placeholder="sad"
            required />
          <label for="cantAmbientes" class="ms-2">Cantidad de Ambientes</label>
        </div>

        <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto col-md-8 text-center">
          <input id="latitud" class="form-control" type="text" name="Latitud" step="any" placeholder="sad"
            pattern="^-?\d{1,2}(,\d+)?$" title="Ingrese una coordenada correta" required />
          <label for="latitud" class="ms-2">Latitud</label>
        </div>

        <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto col-md-8 text-center">
          <input id="longitud" class="form-control" type="text" name="Longitud" step="any" placeholder="sad"
            pattern="^-?\d{1,2}(,\d+)?$" title="Ingrese una coordenada correta" required />
          <label for="longitud" class="ms-2">Longitud</label>
        </div>

        <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto col-md-8 text-center">
          <input id="precio" class="form-control" type="number" name="Precio" step="any" placeholder="sad" required />
          <label for="precio" class="ms-2">Precio</label>
        </div>
      </div>

      <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto col-md-8 text-center">
        <button type="button" class="btn btn-primary mx-auto" style="width: fit-content;"
          onclick="window.location.href = '/Inmuebles'"><i class="fa-solid fa-circle-left"></i></button>
        <button id="btnRegistrar" type="submit" class="btn btn-success mx-auto" style="width: fit-content;"><i
            class="fa-solid fa-building-circle-check"></i></button>
      </div>

    </form>
  </div>
</div>




<script src="~/js/modalCrear.js" asp-append-version="true"></script>
<script src="~/js/modalBuscarPropietaro.js" asp-append-version="true"></script>



<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
  @if (TempData.ContainsKey("AlertMessage") && TempData.ContainsKey("AlertType"))
  {
    var alertMessage = TempData["AlertMessage"];
    var alertType = TempData["AlertType"];
    <text>
        Swal.fire({
          icon: '@alertType',
        title: '@alertMessage',
        showConfirmButton: false,
        timer: 2000 
                  });
    </text>
  }
</script>

Views/Inmuebles/Details.cshtml
@model Inmobiliaria.Models.Inmueble
    
@{
    ViewData["Title"] = "Detalles Inmueble";
}

<div class="text-center ">
    <h1 class="display-4 mb-5">Detalles del Inmueble</h1>
    <div class="text-center ">
       <div class="container mt-4">
           <div class="card mx-auto col-md-8">
               <div class="card-body">
                   <h3>Datos del Inmueble</h3>
        <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
            <input id="direccion" value="@Model.Direccion" class="form-control input-top" type="text" name="Direccion" disabled>
            <label for="direccion" class="ms-2">Dirección</label>
        </div>
        
        <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
            <input id="uso" value="@Model.Uso" class="form-control input-mid" type="text" name="Uso" disabled>
            <label for="uso" class="ms-2">Uso</label>
        </div>
        
        <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
            <input id="tipo" value="@Model.Tipo" class="form-control input-mid" type="text" name="Tipo" disabled>
            <label for="tipo" class="ms-2">Tipo</label>
        </div>
        
        <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
            <input id="cantAmbientes" value="@Model.CantAmbientes" class="form-control input-mid" type="number" name="CantAmbientes" disabled>
            <label for="cantAmbientes" class="ms-2">Cantidad de Ambientes</label>
        </div>
        
        <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
            <input id="latitud" value="@Model.Latitud" class="form-control input-mid" type="text" name="Latitud" step="any" disabled>
            <label for="latitud" class="ms-2">Latitud</label>
        </div>
        
        <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
            <input id="longitud" value="@Model.Longitud" class="form-control input-mid" type="text" name="Longitud" step="any" disabled>
            <label for="longitud" class="ms-2">Longitud</label>
        </div>
        
        <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
            <input id="precio" value="$ @Model.Precio" class="form-control input-bot" type="text" name="Precio" step="any" disabled>
            <label for="precio" class="ms-2">Precio</label>
        </div>
        <h3 class="mt-3">Datos del Propietario</h3>
         <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text- *center">
            <input id="apellido" value="@Model.Propietario.Apellido" class="form-control  input-top" type="text" name="Apellido" placeholder="asd" disabled>
            <label for="apellido" class="ms-2">Apellido</label>
         </div>
         
         <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
             <input id="nombre" value="@Model.Propietario.Nombre" class="form-control  input-mid" type="text" name="Nombre" placeholder="asd" disabled>
             <label for="nombre" class="ms-2">Nombre</label>
         </div>
         
         <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
             <input id="dni" value="@Model.Propietario.Dni" class="form-control  input-mid" type="text" name="Dni" placeholder="asd" disabled>
             <label for="dni" class="ms-2">DNI <span class="fs-7">(formato: XX.XXX.XXX)</span></label>
         </div>
         
         <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
             <input id="telefono" value="@Model.Propietario.Telefono" class="form-control  input-mid" type="tel" name="Telefono" placeholder="asd" disabled>
             <label for="telefono" class="ms-2">Teléfono <span class="fs-7">(Formato +XX XXX-XXXXXXX)</span></label>
         </div>
         
         <div class="d-flex gap-5 form-floating justify-content align-items-center mx-auto  text-center">
             <input id="correo" value="@Model.Propietario.Correo" class="form-control  input-bot" type="email" name="Correo" placeholder="asd" disabled>
             <label for="correo" class="ms-2">Correo</label>
         </div>
                   
               </div>
           </div>
       </div>
    </div>
   <div class="form-group mt-3">
             <button type="button" class="btn btn-primary mx-auto" style="width: fit-content;" onclick="window.history.back()"><i class="fa-solid fa-circle-left"></i></button>         
   </div>

Views/Inmuebles/Index.cshtml
@model List<Inmobiliaria.Models.Inmueble>

@{
    ViewData["Title"] = "Inmuebles";
}

<div class="text-center">
    <h1 class="display-4 mb-5">Inmuebles</h1>

    <table class="table table-striped table-dark table-hover">
        <div class="row d-flex justify-content-between mb-3">
            <div class="col d-flex justify-content-start gap-3 align-items-center ">
                <h5 class="position-relative">Detalle de los Inmuebles @if (ViewBag.NombrePropietario != null)
                    {
                        <span>
                            De @ViewBag.NombrePropietario</span>
                    }
                </h5>
                @if (ViewBag.Disponibles != null)
                {
                    @if (ViewBag.Disponibles)
                    {
                        <a asp-action="Index" class="btn btn-outline-warning ">Mostrar Todos</a>
                    }
                    else if (!ViewBag.Disponibles)
                    {
                        <a asp-action="IndexDisponibles" class="btn btn-outline-warning ">Mostrar Disponibles</a>

                    }
                }


            </div>
            @if (ViewBag.Disponibles != null)
            {
                <div class="col d-flex justify-content-end">
                    <a href="/Inmuebles/Create" class="btn btn-success "> <i class="fa-solid fa-circle-plus "></i></a>
                </div>

            }

        </div>
        <thead>
            <tr>
                <th>Propietario</th>
                <th>Direccion</th>
                <th>Uso</th>
                <th>Tipo</th>
                <th>Ambientes</th>
                <th>Localizacion</th>
                <th>Precio</th>
                <th>Acciones</th>
            </tr>

        </thead>
        @if (Model.Count > 0)
        {
            <tbody>
                @foreach (var Inmueble in Model)
                {

                    <tr>


                        <td>@Inmueble.Propietario.ToString()</td>
                        <td>@Inmueble.Direccion</td>
                        <td>@Inmueble.Uso</td>
                        <td>@Inmueble.Tipo</td>
                        <td>@Inmueble.CantAmbientes</td>
                        <td>@Inmueble.Latitud , @Inmueble.Longitud</td>
                        <td>$@Inmueble.Precio </td>

                        <td class="d-flex gap-2 justify-content-center align-items-center">
                            @if (User.IsInRole("Administrador"))
                            {
                                <form asp-action="Delete" asp-route-id="@Inmueble.Id" onsubmit="return confirmarEliminacion(event)">
                                    <button type="submit"
                                        class="btn btn-outline-danger w-75 h-75 d-flex justify-content-center align-items-center">
                                        <i class="fa-solid fa-trash" title="Borrar"></i>
                                    </button>
                                </form>
                            }
                            <div>
                                <a asp-controller="Inmuebles" asp-action="Update" asp-route-id="@Inmueble.Id"
                                    class="btn btn-outline-primary w-75  d-flex justify-content-center align-items-center"> <i
                                        class="fa-solid fa-pen-to-square" style="cursor:pointer;" title="Modificar"></i> </a>
                            </div>
                            <div>
                                <a asp-controller="Inmuebles" asp-action="Details" asp-route-id="@Inmueble.Id"
                                    class="btn btn-outline-info w-75  d-flex justify-content-center align-items-center"> <i
                                        class="fa-solid fa-eye style=" cursor:pointer;"" title="Detalles"></i> </a>
                            </div>
                            <div>
                                <a asp-controller="Contratos" asp-action="FiltrarPorInmueble" asp-route-id="@Inmueble.Id"
                                    class="btn btn-outline-warning w-75  d-flex justify-content-center align-items-center">
                                    <i class="fa-solid fa-file-contract" title="contratos" style=" cursor:pointer;"></i> </a>
                            </div>
                            <div>
                                <form asp-action="PausarPlay" asp-route-id="@Inmueble.Id">
                                    <button
                                        class="btn  w-75 @(Inmueble.Disponible==true?"btn-outline-success":"btn-outline-danger") d-flex justify-content-center align-items-center"><i
                                            class="fa-solid @(Inmueble.Disponible==true?"fa-circle-pause":"fa-circle-play")"
                                            style="cursor:pointer;" title="Disponibilidad"></i></button>
                                </form>

                            </div>
                        </td>

                    </tr>
                }
            </tbody>
        }
        else
        {
            <tbody>
                <tr>
                    <td colspan="9" class="text-center">No se encontraron Inmuebles para este propietario</td>
                </tr>
            </tbody>
        }

    </table>
    @if (ViewBag.Disponibles == null)
    {
        <div class="form-group mt-3">
            <button type="button" class="btn btn-primary mx-auto" style="width: fit-content;"
                onclick="window.location.href = '/Propietarios'"><i class="fa-solid fa-circle-left"></i></button>
        </div>
    }
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    @if (TempData.ContainsKey("AlertMessage") && TempData.ContainsKey("AlertType"))
    {
        var alertMessage = TempData["AlertMessage"];
        var alertType = TempData["AlertType"];
        <text>
                Swal.fire({
                    icon: '@alertType',
                title: '@alertMessage',
                showConfirmButton: false,
                timer: 2000 // Mostrar durante 2 segundos
                                                      });
        </text>
    }
</script>